### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by rolfn** [klaemo/docker-couchdb#65]
I run the docker container in the following way:
```
docker run -p 5984:5984 -v /var/lib/couchdb:/opt/couchdb/data klaemo/couchdb:2.0-rc2
```
Unfortunately I must set
```
chmod o+rw /var/lib/couchdb 
```
to give CouchDB access to this directory. On the host exist a user "couchdb" and a group "couchdb" (479:477). Is there a way to tell docker/CouchDB writing data with the couchdb id's of the host? Thanks in advance.

**Comment by eav** [comment]
I have the same issue with 2.0-rc3

**Comment by klaemo** [comment]
Yeah this image needs an entrypoint.sh similar to the one in 1.6.1. 

I don't know when I'll get to it, but sometime before 2.0 final 

---
Clemens

**Comment by klaemo** [comment]
Should be fixed in the latest `2.0-rc4` image. Let me know if it works for you.

**Comment by rolfn** [comment]
Sorry, but there are still a lot of problems with the 2.0 docker installation or these are my own mistakes.

I think it is very important to have the ini directory and the data directory  outside of the docker container with access of existing owner/group. 

Here are my steps for running couchdb (mostly faulty):
```
mkdir /etc/couchdb_docker && chown couchdb.couchdb /etc/couchdb_docker
mkdir /var/lib/couchdb_docker && chown couchdb.couchdb /var/lib/couchdb_docker
```
Note: `/etc/couchdb_docker` has now user "467" and group "466" in my case!  Then the first try to start couchdb:
```
/usr/bin/docker rm -f couchdb
/usr/bin/docker run --name couchdb -p 5984:5984 \
          -v /var/lib/couchdb_docker:/opt/couchdb/data \
          -v /etc/couchdb_docker:/opt/couchdb/etc \
          "klaemo/couchdb:2.0-rc4"
```
Result:
```
chmod: cannot access '/opt/couchdb/etc/*.ini': No such file or directory
```
and -- interestingly -- `/etc/couchdb_docker` has now user "1000" and group 
"999"! This is not what I expect. My (host based) user "couchdb" should have "467". 

Next Step: I copied the ini files (tricky stolen from inside the container):
```
cp default.ini local.ini vm.args /etc/couchdb_docker/
```
and start again:
```
/usr/bin/docker rm -f couchdb
/usr/bin/docker run --name couchdb -p 5984:5984 \
          -v /var/lib/couchdb_docker:/opt/couchdb/data \
          -v /etc/couchdb_docker:/opt/couchdb/etc \
          "klaemo/couchdb:2.0-rc4"
```
Result:
```
chmod: cannot access '/opt/couchdb/etc/*.d': No such file or directory
```
Bad! Next step:
```
mkdir /etc/couchdb_docker/local.d
/usr/bin/docker rm -f couchdb
/usr/bin/docker run --name couchdb -p 5984:5984 \
          -v /var/lib/couchdb_docker:/opt/couchdb/data \
          -v /etc/couchdb_docker:/opt/couchdb/etc \
          "klaemo/couchdb:2.0-rc4"
```
Now it seems to work but I wish an easier way. And:
* I want to determine the ownership of the mounted directories not docker.
* I don't want to know existence and content of `default.ini` and `vm.args`.

Maybe docker can analyze two environment variable (e.g. `COUCH_USR` and 
`COUCH_GRP` as numeric values) which are passed via `docker -e COUCH_USR='...'`. 
If they not exist docker can use defaults.

**Comment by klaemo** [comment]
first of all config files should not live in volumes most of the time. secondly, you should mount your config directory into `/opt/couchdb/etc/local.d` and not the root `/opt/couchdb/etc` because the latter will overwrite `default.ini` and `vm.args` (unless you have them in your host directory).

```
docker run --name couchdb -p 5984:5984 -v $(pwd):/opt/couchdb/etc/local.d klaemo/couchdb:2.0-rc4
```
As described in #67.

Everything else concerning docker volumes, permissions etc it might be helpful to consult the docker documentation.

**Comment by rolfn** [comment]
I think your solution is not sufficient. You have only access to your self created local ini file (`clemens.ini`), but Fauxton writes also local config data (to `/opt/couchdb/etc/local.ini`) which are hidden this way.  I want full access to local config data outside of the container just like a native installation.

And the issue with the still wrong permissions of the data files (mounted from `/opt/couchdb/data`) is also not solved. It's not good, if processes creates files owned by no-existing or wrong user. Why not using the clean way with injected environment variables for couchdb's user/group?

**Comment by klaemo** [comment]
Sorry, but you seem to have a different understanding of docker than me. I'm not going to add env vars for setting the user/group. Feel free to fork this repo and implement it in your own project. 

Alternatively, you can prove me wrong and show me another (official) docker database image where the unix user can be set with env vars.
